version: '3.8'

services:
  pypi-server:
    image: pypiserver/pypiserver:latest
    container_name: private-pypi
    ports:
      - "8080:8080"
    volumes:
      - ./packages:/data/packages
      - ./auth:/data/auth
    environment:
      - PYPI_PASSWORDS=/data/auth/.htpasswd
    command: >
      -P /data/auth/.htpasswd
      -a update,download,list
      -o
      --hash-algo sha256
      /data/packages
    restart: unless-stopped
    networks:
      - pypi-network

  nginx:
    image: nginx:alpine
    container_name: pypi-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - pypi-server
    restart: unless-stopped
    networks:
      - pypi-network

networks:
  pypi-network:
    driver: bridge

volumes:
  packages:
  auth:
